spring.data.mongodb.uri=${MONGODB_URI:mongodb://mongo:27017/web-game}
spring.data.mongodb.database=${MONGODB_DATABASE:web-game}
server.port=${PORT:8080}

# JWT Configuration
app.jwtSecret=${JWT_SECRET:SuperSecretKeyForWebGameThatIsVeryLongAndSecure123456789}
app.jwtExpirationMs=${JWT_EXPIRATION_MS:86400000}